### ISSUE TITLE
[Readme] Link to article from hash3liZer broken

### ISSUE THREAD

**Issue by Splines** [gombossb/rickrollAP#1]
In the Readme:
> Kudos to hash3liZer for his article on shellvoide.com, it's helped me a lot with this project.

The [link](https://www.shellvoide.com/wifi/how-to-setup-captive-portal-login-with-rogue-ap-nginx/) is broken 😥

**Comment by gombossb** [comment]
I changed the link to an archived version on Wayback Machine
